import AppKit
import UniformTypeIdentifiers

enum ClipboardFile {
    static func create(
        from pasteboard: NSPasteboard = .general,
        in directory: URL = FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask)[0]
    ) throws -> URL? {
        let file: (data: Data, extension: String)?

        if let data = pasteboard.data(forType: .png) {
            file = (data, "png")
        } else if let data = data(on: pasteboard, type: UTType.jpeg) {
            file = (data, "jpg")
        } else if let data = data(on: pasteboard, type: UTType.gif) {
            file = (data, "gif")
        } else if let data = data(on: pasteboard, type: UTType.webP) {
            file = (data, "webp")
        } else if let data = pasteboard.data(forType: .tiff),
                  let image = NSBitmapImageRep(data: data),
                  let png = image.representation(using: .png, properties: [:]) {
            file = (png, "png")
        } else if let media = firstSupportedMediaData(on: pasteboard) {
            file = media
        } else if let data = pasteboard.data(forType: .pdf) {
            file = (data, "pdf")
        } else if let data = pasteboard.data(forType: .rtf) {
            file = (data, "rtf")
        } else if let data = pasteboard.data(forType: .html) {
            file = (data, "html")
        } else if let urlString = pasteboard.string(forType: .URL), URL(string: urlString) != nil {
            file = (try webLocationData(urlString), "webloc")
        } else if let text = pasteboard.string(forType: .string) {
            file = (Data(text.utf8), "txt")
        } else {
            file = firstOtherData(on: pasteboard)
        }

        guard let file else { return nil }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = availableURL(in: directory, extension: file.extension)
        try file.data.write(to: url, options: .atomic)
        return url
    }

    private static func data(on pasteboard: NSPasteboard, type: UTType) -> Data? {
        pasteboard.data(forType: NSPasteboard.PasteboardType(type.identifier))
    }

    private static func firstSupportedMediaData(on pasteboard: NSPasteboard) -> (Data, String)? {
        let types: [(UTType, String)] = [
            (.quickTimeMovie, "mov"),
            (.mpeg4Movie, "mp4"),
            (UTType(importedAs: "org.webmproject.webm"), "webm"),
        ]
        return types.lazy.compactMap { type, fileExtension in
            data(on: pasteboard, type: type).map { ($0, fileExtension) }
        }.first
    }

    private static func firstOtherData(on pasteboard: NSPasteboard) -> (Data, String)? {
        let ignoredTypes = Set([
            NSPasteboard.PasteboardType.fileURL.rawValue,
            NSPasteboard.PasteboardType.URL.rawValue,
            NSPasteboard.PasteboardType.string.rawValue,
            "org.nspasteboard.AutoGeneratedType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
        ])
        return (pasteboard.types ?? []).lazy.compactMap { type in
            guard !ignoredTypes.contains(type.rawValue), let data = pasteboard.data(forType: type), !data.isEmpty else {
                return nil
            }
            let fileExtension = UTType(type.rawValue)?.preferredFilenameExtension ?? "data"
            return (data, fileExtension)
        }.first
    }

    private static func webLocationData(_ urlString: String) throws -> Data {
        try PropertyListSerialization.data(
            fromPropertyList: ["URL": urlString],
            format: .xml,
            options: 0
        )
    }

    private static func availableURL(in directory: URL, extension fileExtension: String) -> URL {
        let baseName = "Clipboard"
        var candidate = directory.appending(path: "\(baseName).\(fileExtension)")
        var suffix = 2
        while FileManager.default.fileExists(atPath: candidate.path) {
            candidate = directory.appending(path: "\(baseName) \(suffix).\(fileExtension)")
            suffix += 1
        }
        return candidate
    }
}
